"use client"

import * as React from "react"
import { useParams } from "next/navigation"
import Link from "next/link"
import { toast } from "sonner"
import {
  Sparkles,
  Download,
  FileText,
  Clock,
  Layers,
  Home,
  Compass,
  ArrowRight,
  Loader2,
  Calendar,
} from "lucide-react"

import { Button } from "@/components/ui/button"
import { BlueprintGantt } from "@/components/client/BlueprintGantt"
import dynamic from "next/dynamic"

const BlueprintSVG = dynamic(() => import("@/components/client/BlueprintSVG"), {
  ssr: false,
  loading: () => (
    <div className="h-[400px] flex items-center justify-center bg-slate-50 rounded-xl border border-dashed">
      <div className="animate-spin rounded-full h-8 w-8 border-4 border-orange/20 border-t-orange"></div>
    </div>
  ),
})
import { downloadBlueprintPDF } from "@/lib/blueprint-pdf"
import { cn } from "@/lib/utils/cn"

function formatIndianNumber(num: number): string {
  return new Intl.NumberFormat("en-IN", {
    maximumFractionDigits: 0,
  }).format(num)
}

export default function SharedBlueprintPage() {
  const { shareId } = useParams()
  const [loading, setLoading] = React.useState<boolean>(true)
  const [error, setError] = React.useState<string | null>(null)
  const [data, setData] = React.useState<any | null>(null)
  
  const [activeTab, setActiveTab] = React.useState<"floorPlan" | "cost" | "materials" | "timeline" | "recommendations" >("floorPlan")
  const [selectedFloor, setSelectedFloor] = React.useState<number>(1)

  React.useEffect(() => {
    if (!shareId) return

    const fetchSharedBlueprint = async () => {
      try {
        setLoading(true)
        const response = await fetch(`/api/blueprint/${shareId}`)
        if (!response.ok) {
          const err = await response.json()
          throw new Error(err.error || "Failed to load blueprint")
        }
        const result = await response.json()
        if (result.success) {
          setData(result.data)
        } else {
          throw new Error(result.message || "Could not retrieve blueprint")
        }
      } catch (err: any) {
        console.error(err)
        setError(err.message || "Failed to load shared blueprint")
      } finally {
        setLoading(false)
      }
    }

    fetchSharedBlueprint()
  }, [shareId])

  if (loading) {
    return (
      <div className="min-h-screen bg-[#FDF8F2] flex flex-col items-center justify-center space-y-3 font-body p-6">
        <Loader2 className="h-8 w-8 text-[#E85D04] animate-spin" />
        <p className="text-sm font-semibold text-[#6F5B4B]">Loading shared construction blueprint...</p>
      </div>
    )
  }

  if (error || !data) {
    return (
      <div className="min-h-screen bg-[#FDF8F2] flex flex-col items-center justify-center space-y-4 font-body p-6 text-center">
        <div className="text-4xl">⚠️</div>
        <h3 className="font-serif text-lg font-bold text-[#3D2B1F]">Blueprint Unavailable</h3>
        <p className="text-xs text-[#6F5B4B] max-w-sm leading-relaxed">
          {error || "The requested blueprint save could not be found or has been removed."}
        </p>
        <Link href="/signup">
          <Button className="bg-[#E85D04] text-white hover:bg-[#D45203] text-xs font-semibold px-4 py-2">
            Create Your Own Blueprint
          </Button>
        </Link>
      </div>
    )
  }

  const { blueprintData, formData, createdAt, userName } = data
  const dateStr = new Date(createdAt).toLocaleDateString("en-IN", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })

  return (
    <div className="min-h-screen bg-[#FDF8F2]/60 font-body text-[#3D2B1F] flex flex-col">
      
      {/* Top Banner */}
      <div className="bg-[#E85D04] text-white py-2.5 px-4 text-center text-xs font-semibold shadow-xs flex items-center justify-center gap-2">
        <Sparkles className="h-4.5 w-4.5 animate-pulse" />
        <span>Blueprint generated by HomeEvo AI for <strong>{userName}</strong></span>
      </div>

      {/* Main Content Area */}
      <main className="flex-1 max-w-4xl mx-auto w-full p-4 md:p-8 space-y-6">
        
        {/* Header Block */}
        <div className="bg-white border border-[#E85D04]/10 rounded-2xl p-5 md:p-6 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="space-y-1">
            <span className="text-[9px] bg-[#FDF8F2] border border-[#E85D04]/10 text-[#E85D04] font-bold px-2 py-0.5 rounded-full">
              {formData.style} Style
            </span>
            <h1 className="font-serif text-xl md:text-2xl font-bold text-[#3D2B1F] pt-1">
              AI Construction Plan Spec
            </h1>
            <p className="text-3xs md:text-2xs text-[#6F5B4B] font-medium flex items-center gap-1.5 pt-0.5">
              <Calendar className="h-3 w-3" /> Shared on {dateStr} • Generated for {formData.landSize} sq ft plot
            </p>
          </div>

          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={() => {
              toast.promise(downloadBlueprintPDF(blueprintData), {
                loading: "Generating PDF...",
                success: "PDF downloaded!",
                error: "Error downloading PDF.",
              })
            }}
            className="text-xs font-semibold text-[#E85D04] border-[#E85D04]/20 hover:bg-[#FDF8F2] self-start md:self-center"
          >
            <Download className="h-3.5 w-3.5 mr-1" /> Download PDF
          </Button>
        </div>

        {/* Tab Controls */}
        <div className="flex bg-[#FDF8F2] border border-border/80 p-1 rounded-xl w-full overflow-x-auto whitespace-nowrap scrollbar-none gap-1">
          {[
            { id: "floorPlan", name: "Floor Plan", icon: Home },
            { id: "cost", name: "Cost Estimate", icon: Layers },
            { id: "materials", name: "Materials", icon: FileText },
            { id: "timeline", name: "Timeline", icon: Clock },
            { id: "recommendations", name: "Recommendations", icon: Compass },
          ].map((tab) => (
            <button
              key={tab.id}
              type="button"
              onClick={() => setActiveTab(tab.id as any)}
              className={cn(
                "flex items-center gap-1.5 px-3.5 py-2 text-xs font-bold rounded-lg transition-all duration-200",
                activeTab === tab.id
                  ? "bg-[#E85D04] text-white shadow-2xs"
                  : "text-[#6F5B4B] hover:bg-[#FDF8F2]/60"
              )}
            >
              <tab.icon className="h-3.5 w-3.5" />
              <span>{tab.name}</span>
            </button>
          ))}
        </div>

        {/* TAB CONTENTS */}
        
        {/* Floor Plan */}
        {activeTab === "floorPlan" && blueprintData.floorPlan && (
          <div className="space-y-4">
            <BlueprintSVG
              floorPlan={blueprintData.floorPlan}
              selectedFloor={selectedFloor}
              onFloorChange={setSelectedFloor}
            />

            <div className="bg-white border border-border/60 rounded-xl p-4 shadow-2xs grid grid-cols-3 gap-4 text-center">
              <div>
                <span className="block text-[10px] font-bold text-[#6F5B4B] uppercase">Built Area</span>
                <span className="text-sm md:text-base font-bold text-[#E85D04]">{blueprintData.floorPlan.totalArea} sq ft</span>
              </div>
              <div>
                <span className="block text-[10px] font-bold text-[#6F5B4B] uppercase">Total Rooms</span>
                <span className="text-sm md:text-base font-bold text-[#3D2B1F]">
                  {blueprintData.floorPlan.rooms.filter((r: any) => r.floor === selectedFloor).length}
                </span>
              </div>
              <div>
                <span className="block text-[10px] font-bold text-[#6F5B4B] uppercase">Total Floors</span>
                <span className="text-sm md:text-base font-bold text-[#3D2B1F]">{blueprintData.floorPlan.floors}</span>
              </div>
            </div>
          </div>
        )}

        {/* Cost estimate table */}
        {activeTab === "cost" && blueprintData.costEstimate && (
          <div className="bg-white border border-border/60 rounded-xl p-5 shadow-2xs space-y-4">
            <h4 className="font-serif text-sm font-bold text-[#3D2B1F] flex items-center gap-1.5 border-b pb-2">
              <Layers className="h-4 w-4 text-[#E85D04]" /> Estimations Breakdown
            </h4>

            <div className="overflow-x-auto border rounded-lg border-border/60">
              <table className="w-full text-left text-xs border-collapse">
                <thead>
                  <tr className="bg-slate-50 border-b border-border text-[#6F5B4B] font-bold text-[10px] uppercase tracking-wider">
                    <th className="py-2.5 px-3">Category / Item</th>
                    <th className="py-2.5 px-3">Qty</th>
                    <th className="py-2.5 px-3">Unit</th>
                    <th className="py-2.5 px-3 text-right">Unit Cost</th>
                    <th className="py-2.5 px-3 text-right">Total</th>
                  </tr>
                </thead>
                <tbody>
                  {(() => {
                    const categories: Record<string, any[]> = {}
                    blueprintData.costEstimate.items.forEach((item: any) => {
                      if (!categories[item.category]) categories[item.category] = []
                      categories[item.category].push(item)
                    })

                    return Object.entries(categories).map(([cat, items]) => (
                      <React.Fragment key={cat}>
                        <tr className="bg-[#FDF8F2]/50 border-b border-border/60">
                          <td colSpan={5} className="py-2 px-3 font-bold text-[#E85D04] uppercase text-[10px]">
                            {cat}
                          </td>
                        </tr>
                        {items.map((item, idx) => (
                          <tr key={idx} className="border-b border-border/30">
                            <td className="py-2 px-4 text-[#3D2B1F] font-semibold">{item.item}</td>
                            <td className="py-2 px-3 text-[#6F5B4B]">{item.quantity.toLocaleString("en-IN")}</td>
                            <td className="py-2 px-3 text-[#6F5B4B]">{item.unit}</td>
                            <td className="py-2 px-3 text-right text-[#6F5B4B]">₹{formatIndianNumber(item.unitCost)}</td>
                            <td className="py-2 px-3 text-right text-[#3D2B1F] font-bold">₹{formatIndianNumber(item.totalCost)}</td>
                          </tr>
                        ))}
                      </React.Fragment>
                    ))
                  })()}
                </tbody>
                <tfoot>
                  <tr className="border-t border-border/80">
                    <td colSpan={4} className="py-2 px-3 text-right font-bold text-[#6F5B4B]">Subtotal:</td>
                    <td className="py-2 px-3 text-right font-bold text-[#3D2B1F]">₹{formatIndianNumber(blueprintData.costEstimate.subtotal)}</td>
                  </tr>
                  <tr className="border-t border-border/30">
                    <td colSpan={4} className="py-2 px-3 text-right font-bold text-amber-600">Contingency (10%):</td>
                    <td className="py-2 px-3 text-right font-bold text-amber-600">₹{formatIndianNumber(blueprintData.costEstimate.contingency)}</td>
                  </tr>
                  <tr className="border-t-2 border-border/80 bg-slate-50/50">
                    <td colSpan={4} className="py-3 px-3 text-right font-serif text-sm font-bold text-[#3D2B1F]">Grand Total:</td>
                    <td className="py-3 px-3 text-right font-serif text-base font-bold text-[#E85D04]">₹{formatIndianNumber(blueprintData.costEstimate.grandTotal)}</td>
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>
        )}

        {/* Materials */}
        {activeTab === "materials" && blueprintData.materialsList && (
          <div className="bg-white border border-border/60 rounded-xl p-5 shadow-2xs space-y-4">
            <h4 className="font-serif text-sm font-bold text-[#3D2B1F] flex items-center gap-1.5 border-b pb-2">
              <FileText className="h-4 w-4 text-[#E85D04]" /> Required Materials
            </h4>

            <div className="overflow-x-auto border rounded-lg border-border/60">
              <table className="w-full text-left text-xs border-collapse">
                <thead>
                  <tr className="bg-slate-50 border-b border-border text-[#6F5B4B] font-bold text-[10px] uppercase tracking-wider">
                    <th className="py-2.5 px-3">Material</th>
                    <th className="py-2.5 px-3">Quantity</th>
                    <th className="py-2.5 px-3">Unit</th>
                    <th className="py-2.5 px-3 text-right">Est. Cost</th>
                    <th className="py-2.5 px-3">Sourcing Notes</th>
                  </tr>
                </thead>
                <tbody>
                  {blueprintData.materialsList.map((m: any, idx: number) => (
                    <tr key={idx} className="border-b border-border/30">
                      <td className="py-2.5 px-3 font-semibold text-[#3D2B1F]">{m.material}</td>
                      <td className="py-2.5 px-3 text-[#6F5B4B]">{m.quantity.toLocaleString("en-IN")}</td>
                      <td className="py-2.5 px-3 text-[#6F5B4B]">{m.unit}</td>
                      <td className="py-2.5 px-3 text-right font-bold text-[#E85D04]">₹{formatIndianNumber(m.estimatedCost)}</td>
                      <td className="py-2.5 px-3 text-[10px] text-[#6F5B4B] max-w-[200px] truncate" title={m.notes}>{m.notes}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Timeline */}
        {activeTab === "timeline" && blueprintData.timeline && (
          <div className="space-y-4">
            <BlueprintGantt timeline={blueprintData.timeline} />

            <div className="space-y-3">
              {blueprintData.timeline.phases.map((phase: any, idx: number) => (
                <div key={idx} className={cn("border border-border/50 rounded-xl p-4 shadow-3xs flex flex-col md:flex-row gap-4 items-start md:items-center justify-between", idx % 2 === 0 ? "bg-white" : "bg-[#FDF8F2]/20")}>
                  <div className="space-y-1">
                    <h5 className="text-xs font-bold text-[#3D2B1F] flex items-center gap-2">
                      <span className="w-5 h-5 rounded-full bg-[#FDF8F2] text-[#E85D04] flex items-center justify-center text-[10px] font-bold border border-[#E85D04]/25">
                        {idx + 1}
                      </span>
                      {phase.name}
                    </h5>
                    <p className="text-[10px] text-[#6F5B4B]">
                      {phase.description}
                    </p>
                  </div>
                  <span className="text-xs font-bold text-[#E85D04] bg-[#FDF8F2]/60 px-3 py-1.5 rounded-lg shrink-0 border border-[#E85D04]/10">
                    {phase.weeks} Weeks
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Recommendations */}
        {activeTab === "recommendations" && blueprintData.recommendations && (
          <div className="bg-white border border-border/60 rounded-xl p-5 shadow-2xs space-y-4">
            <h4 className="font-serif text-sm font-bold text-[#3D2B1F] flex items-center gap-1.5 border-b pb-2">
              <Compass className="h-4 w-4 text-[#E85D04]" /> AP Sourcing Guidelines
            </h4>
            <div className="space-y-3">
              {blueprintData.recommendations.map((rec: string, idx: number) => (
                <div key={idx} className="flex items-start gap-3 p-2 rounded hover:bg-slate-50">
                  <span className="w-5 h-5 rounded-full bg-[#E85D04] text-white flex items-center justify-center text-[10px] font-bold shrink-0">
                    {idx + 1}
                  </span>
                  <p className="text-xs text-[#6F5B4B] leading-relaxed">
                    {rec}
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Call To Action Card */}
        <div className="bg-white border border-[#E85D04]/20 rounded-2xl p-6 text-center space-y-4 shadow-sm">
          <div className="space-y-1.5">
            <h3 className="font-serif text-base font-bold text-[#3D2B1F]">
              Build Your Own Custom Construction Plan
            </h3>
            <p className="text-xs text-[#6F5B4B] max-w-md mx-auto">
              HomeEvo's AI generator creates building designs tailored exactly to your requirements, budget range, and location rules in Andhra Pradesh.
            </p>
          </div>
          <Link href="/signup">
            <Button className="bg-[#E85D04] text-white hover:bg-[#D45203] text-xs font-bold px-6 py-2.5 shadow-xs inline-flex items-center gap-2">
              Create Your Free Account <ArrowRight className="h-4 w-4" />
            </Button>
          </Link>
        </div>

      </main>

      {/* Footer */}
      <footer className="bg-white border-t py-4 text-center text-[10px] text-[#6F5B4B] mt-12">
        <p>© 2026 HomeEvo Platform. Connecting homeowners with professional contractors in Andhra Pradesh.</p>
      </footer>
    </div>
  )
}
